#cloud-config
packages:
  - jq
  # - unzip

  
# runcmd:
#   - `wget https://releases.hashicorp.com/nomad/0.12.5+ent/nomad_0.12.5+ent_linux_amd64.zip`
#   - `unzip nomad_0.12.5+ent_linux_amd64.zip`
#   - `mv nomad /usr/local/bin/`

write_files:
    - path: /etc/consul.d/config.json
      content: ${consul_conf}
      permissions: '0644'
      owner: consul:consul
      encoding: b64
    - path: /etc/environment
      content: |
        CONSUL_HTTP_ADDR=http://${ip_address}:8500
      append: true  

write_files:
  - path: /etc/nomad.d/config.json
    content: ${consul_conf}
    permissions: '0644'
    owner: nomad:nomad
    encoding: b64
  - path: /etc/environment
    content: |
      NOMAD_API=http://${ip_address}:4646
    append: true

runcmd:
  - systemctl enable consul
  - systemctl restart consul  
  - systemctl enable nomad
  - systemctl restart nomad
